version: '3'

services:

  traefik:
    image: traefik:v2.10
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=emil4154515@gmail.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      #- --accesslog
      #- --log
      - --api
    networks:
      - web

  portfolio_api:
    build: ./portfolio_api
    container_name: portfolio_api
    restart: always
    environment:
      DEBUG: 1
      ALLOWED_HOSTS: 'example.com'
      CSRF_TRUSTED_ORIGINS: 'https://api.example.com'
      SECRET_KEY: 'django-insecure-%9l#khafj$!()iswq2ov*g+_q6!8y!l7!oxap6cawu28u391p1'
    labels:
      - traefik.enable=true
      - traefik.http.services.portfolio_api.loadbalancer.server.port=80
      - traefik.http.routers.app-http_portfolio_api.entrypoints=http
      - traefik.http.routers.app-http_portfolio_api.rule=Host(`api.example.com`)
      - traefik.docker.network=web
      - traefik.http.routers.app-https_portfolio_api.entrypoints=https
      - traefik.http.routers.app-https_portfolio_api.rule=Host(`api.example.com`)
      - traefik.http.routers.app-https_portfolio_api.tls=true
      - traefik.http.routers.app-https_portfolio_api.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.app-http_portfolio_api.middlewares=https-redirect
    networks:
      - internal
      - web
    volumes:
      - ./portfolio_api:/portfolio_api

  portfolio_front:
    build: ./portfolio_front
    container_name: portfolio_front
    environment:
      NUXT_PUBLIC_SITE_URL: 'https://example.com'
      NUXT_PUBLIC_API_BASE: 'https://api.example.com'
      NUXT_PUBLIC_SITE_PRIMARY_COLOR: '#ff9638'
      NUXT_PUBLIC_SITE_NAME: 'My Portfolio'
      NUXT_PUBLIC_ICON_LETTER: 'A'
      NUXT_PUBLIC_OWNER_NAME: 'Alex'
      NUXT_PUBLIC_OWNER_LAST_NAME: 'Smith'
      NUXT_IMAGE_DOMAIN: 'api.example.com'
      NUXT_PUBLIC_GTAG_ID: G-XXXXXXXXXX
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.emil_portfolio_front.loadbalancer.server.port=3000
      - traefik.http.routers.app-http_portfolio_front.entrypoints=http
      - traefik.http.routers.app-http_portfolio_front.rule=Host(`example.com`)
      - traefik.docker.network=web
      - traefik.http.routers.app-https_portfolio_front.entrypoints=https
      - traefik.http.routers.app-https_portfolio_front.rule=Host(`example.com`)
      - traefik.http.routers.app-https_portfolio_front.tls=true
      - traefik.http.routers.app-https_portfolio_front.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.app-http_portfolio_front.middlewares=https-redirect
    networks:
      - internal
      - web
    volumes:
      - ./portfolio_front:/portfolio_front

networks:
  web:
    external: true
  internal:
    external: false
